---
- name: manage uptimerobot monitor entries
  tags: uptimerobot
  uptimerobot:
    api_key: "{{ uptimerobot_api_key }}"
    name: "{{ item.name }}"
    url: "{{ item.url }}"
    alert_contacts: "{{ alert_contacts }}"
    state: "{{ item.state }}"
  with_items:
  - "{{ uptimerobot_targets }}"
